# Generated by Django 2.0 on 2022-10-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动着id')),
                ('sid', models.IntegerField(verbose_name='被滑动着id')),
                ('status', models.CharField(choices=[('dislike', '不喜欢'), ('like', '喜欢'), ('super_like', '超级喜欢')], max_length=8)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
