# Generated by Django 2.0 on 2022-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiped',
            name='status',
            field=models.CharField(choices=[('dislike', '不喜欢'), ('like', '喜欢'), ('super_like', '超级喜欢')], max_length=10),
        ),
    ]
