# Generated by Django 2.0 on 2022-09-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(verbose_name='最小查询范围')),
                ('max_distance', models.IntegerField(verbose_name='最大查询范围')),
                ('min_dating_age', models.CharField(default=18, max_length=3, verbose_name='最小匹配年龄')),
                ('max_dating_age', models.CharField(default=45, max_length=3, verbose_name='最大匹配年龄')),
                ('dating_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8)),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_match', models.BooleanField(default=True, verbose_name='不让未匹配的人看相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=18, unique=True)),
                ('phonenum', models.CharField(max_length=12, unique=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8)),
                ('avatar', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
            ],
        ),
    ]
