# Generated by Django 2.0 on 2022-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220924_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.IntegerField(default=200, verbose_name='最大查询范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.IntegerField(default=0, verbose_name='最小查询范围'),
        ),
    ]
